name: apod
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - certifi=2025.1.31
  - cffi=1.17.1
  - charset-normalizer=3.4.1
  - freetype=2.13.3
  - h2=4.2.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - idna=3.10
  - lcms2=2.17
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libdeflate=1.23
  - libexpat=2.7.0
  - libffi=3.4.6
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgomp=14.2.0
  - libjpeg-turbo=3.0.0
  - liblzma=5.8.1
  - libnsl=2.0.1
  - libpng=1.6.47
  - libsqlite=3.49.1
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libtiff=4.7.0
  - libuuid=2.38.1
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - ncurses=6.5
  - openjpeg=2.5.3
  - openssl=3.5.0
  - pillow=11.1.0
  - pip=25.0.1
  - pthread-stubs=0.4
  - pycparser=2.22
  - pysocks=1.7.1
  - python=3.12.10
  - python_abi=3.12
  - readline=8.2
  - requests=2.32.3
  - setuptools=78.1.0
  - tk=8.6.13
  - tzdata=2025b
  - urllib3=2.4.0
  - wheel=0.45.1
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - zstandard=0.23.0
  - zstd=1.5.7

